### ISSUE TITLE
Define Organization Resource Type

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/webcentral-nova#6]
The Organization Resource type needs to provide the data for this part of the new Directory that will replace A-Z.

![directory-wireframes2_pdf__page_2_of_5_](https://user-images.githubusercontent.com/385234/50930280-cf3c8300-141c-11e9-8d81-0cbf68372383.png)

**Organization**
Department/unit name:
Abbreviation: (text)
Summary of Department: (optional w/ character limit)
Part of: (select parent unit drop down or autocomplete)
Type (select list): Division | Academic Department | Student Service | Lab | Center

**Address**
Address 1 [Building Name - links to Campus Bird]
Address 2: [Suite 200]
Address 3: [Campus Box 584 UCB]

![img_20190109_135757](https://user-images.githubusercontent.com/385234/50929673-1164c500-141b-11e9-9901-35581201553f.jpg)

**Contacts**
The UX we want is something like the combined the functionality of https://packagist.org/packages/fourstacks/nova-repeatable-fields and https://novapackages.com/packages/epartment/nova-dependency-container.

We are aware that storing JSON in text wouldn't be searchable in the resource type view "out of the box" or easily exported in a list like "all Twitter accounts". This is an acceptable compromise to get the desired UX.

Label
Type (Phone, Website, Email, Social... base on the selection, additional fields are hidden/shown) 
Phone (text)
Website (url)
Email (email)
Social (url)

**Comment by alexfinnarn** [comment]
Adding the value that gets stored for the "Contacts" field.

```
value: "[{"contact_label":"Primary Phone","contact_type":"phone","contact_value":"303-555-1212"},{"contact_label":"Website","contact_type":"website","contact_value":"https:\/\/www.colorado.edu\/strrategicrelations"},{"contact_label":"Email","contact_type":"email","contact_value":"strategicrelations@colorado.edu"},{"contact_label":"Twitter","contact_type":"social_media","contact_value":"https:\/\/twitter.com\/strategicrelations"}]",
```

If that data is sent as-is to a consumer, then every consumer will need to know how to unpack it and validate the transformed data. This wouldn't be ideal since then the consumer needs to know more than printing a value if it exists and where that value should go in a template. Also, as mentioned above, data about all the emails, social media accounts, etc. can't be queried from the API. 

If UX is the only reason to set things up this way for the Contacts field, I would suggest using Accessors and Mutators to retrieve and set that value. https://laravel.com/docs/5.7/eloquent-mutators

Then, `label`, `type`, and `value` can be grouped into contact fields. If you don't want to mess around with Eloquent and Active Record that much or it gets hairy, you could still store the same value in the Organizations table but create another table in the database that you set with a mutator using plain SQL. The API would interact with that additional table but Nova would just load the contact field like normal.

I don't think Nova will be involved at all in the API-side of things so transforming of the data could be done via something like the Fractal package or Resources.

https://laravel.com/docs/5.7/eloquent-resources#writing-resources
https://github.com/spatie/laravel-fractal

I'm obviously biased towards making it as easy for any client to get the data in a structured way, but I also think tying data storage to a UI is not a best practice. Also, there will inevitably be a need at some point to return the resources/models/thingy-s in a non-default way to how they are stored. So, it makes sense to think about data transformation and normalization now.
